### ISSUE TITLE
Type implementation progress

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/schema-org#1]
- [x] Thing
    - [x] Action
        - [x] AchieveAction
            - [x] LoseAction
            - [x] TieAction
            - [x] WinAction
        - [x] AssessAction
            - [x] ChooseAction
                - [x] VoteAction
            - [x] IgnoreAction
            - [x] ReactAction
                - [x] AgreeAction
                - [x] DisagreeAction
                - [x] DislikeAction
                - [x] EndorseAction
                - [x] LikeAction
                - [x] WantAction
            - [x] ReviewAction
        - [x] ConsumeAction
            - [x] DrinkAction
            - [x] EatAction
            - [x] InstallAction
            - [x] ListenAction
            - [x] ReadAction
            - [x] UseAction
                - [x] WearAction
            - [x] ViewAction
            - [x] WatchAction
        - [x] ControlAction
            - [x] ActivateAction
            - [x] DeactivateAction
            - [x] ResumeAction
            - [x] SuspendAction
        - [x] CreateAction
            - [x] CookAction
            - [x] DrawAction
            - [x] FilmAction
            - [x] PaintAction
            - [x] PhotographAction
            - [x] WriteAction
        - [x] FindAction
            - [x] CheckAction
            - [x] DiscoverAction
            - [x] TrackAction
        - [x] InteractAction
            - [x] BefriendAction
            - [x] CommunicateAction
                - [x] AskAction
                - [x] CheckInAction
                - [x] CheckOutAction
                - [x] CommentAction
                - [x] InformAction
                    - [x] ConfirmAction
                    - [x] RsvpAction
                - [x] InviteAction
                - [x] ReplyAction
                - [x] ShareAction
            - [x] FollowAction
            - [x] JoinAction
            - [x] LeaveAction
            - [x] MarryAction
            - [x] RegisterAction
            - [x] SubscribeAction
            - [x] UnRegisterAction
        - [x] MoveAction
            - [x] ArriveAction
            - [x] DepartAction
            - [x] TravelAction
        - [x] OrganizeAction
            - [x] AllocateAction
                - [x] AcceptAction
                - [x] AssignAction
                - [x] AuthorizeAction
                - [x] RejectAction
            - [x] ApplyAction
            - [x] BookmarkAction
            - [x] PlanAction
                - [x] CancelAction
                - [x] ReserveAction
                - [x] ScheduleAction
        - [x] PlayAction
            - [x] ExerciseAction
            - [x] PerformAction
        - [x] SearchAction
        - [x] TradeAction
            - [x] BuyAction
            - [x] DonateAction
            - [x] OrderAction
            - [x] PayAction
            - [x] QuoteAction
            - [x] RentAction
            - [x] SellAction
            - [x] TipAction
        - [x] TransferAction
            - [x] BorrowAction
            - [x] DownloadAction
            - [x] GiveAction
            - [x] LendAction
            - [x] ReceiveAction
            - [x] ReturnAction
            - [x] SendAction
            - [x] TakeAction
        - [x] UpdateAction
            - [x] AddAction
                - [x] InsertAction
                    - [x] AppendAction
                    - [x] PrependAction
            - [x] DeleteAction
            - [x] ReplaceAction
    - [x] CreativeWork
        - [x] Article
            - [x] NewsArticle
            - [x] Report
            - [x] ScholarlyArticle
            - [x] SocialMediaPosting
                - [x] BlogPosting
                    - [x] LiveBlogPosting
                - [x] DiscussionForumPosting
            - [x] TechArticle
                - [x] APIReference
        - [x] Blog
        - [x] Book
        - [x] Clip
            - [x] MovieClip
            - [x] RadioClip
            - [x] TVClip
            - [x] VideoGameClip
        - [x] Comment
            - [x] Answer
        - [x] Conversation
        - [x] CreativeWorkSeason
            - [x] RadioSeason
            - [x] TVSeason
        - [x] CreativeWorkSeries
            - [x] BookSeries
            - [x] MovieSeries
            - [x] Periodical
            - [x] RadioSeries
            - [x] TVSeries
            - [x] VideoGameSeries
        - [x] DataCatalog
        - [x] Dataset
            - [x] DataFeed
        - [x] DigitalDocument
            - [x] NoteDigitalDocument
            - [x] PresentationDigitalDocument
            - [x] SpreadsheetDigitalDocument
            - [x] TextDigitalDocument
        - [x] Episode
            - [x] RadioEpisode
            - [x] TVEpisode
        - [x] Game
            - [x] VideoGame
        - [x] Map
        - [x] MediaObject
            - [x] AudioObject
            - [x] DataDownload
            - [x] ImageObject
                - [x] Barcode
            - [x] MusicVideoObject
            - [x] VideoObject
        - [x] Message
            - [x] EmailMessage
        - [x] Movie
        - [x] MusicComposition
        - [x] MusicPlaylist
            - [x] MusicAlbum
            - [x] MusicRelease
        - [x] MusicRecording
        - [x] Painting
        - [x] Photograph
        - [x] PublicationIssue
        - [x] PublicationVolume
        - [x] Question
        - [x] Recipe
        - [x] Review
        - [x] Sculpture
        - [x] Series
        - [x] SoftwareApplication
            - [x] MobileApplication
            - [x] VideoGame
            - [x] WebApplication
        - [x] SoftwareSourceCode
        - [x] TVSeason
        - [x] TVSeries
        - [x] VisualArtwork
        - [x] WebPage
            - [x] AboutPage
            - [x] CheckoutPage
            - [x] CollectionPage
                - [x] ImageGallery
                - [x] VideoGallery
            - [x] ContactPage
            - [x] ItemPage
            - [x] ProfilePage
            - [x] QAPage
            - [x] SearchResultsPage
        - [x] WebPageElement
            - [x] SiteNavigationElement
            - [x] Table
            - [x] WPAdBlock
            - [x] WPFooter
            - [x] WPHeader
            - [x] WPSideBar
        - [x] WebSite
    - [x] Event
        - [x] BusinessEvent
        - [x] ChildrensEvent
        - [x] ComedyEvent
        - [x] DanceEvent
        - [x] DeliveryEvent
        - [x] EducationEvent
        - [x] ExhibitionEvent
        - [x] Festival
        - [x] FoodEvent
        - [x] LiteraryEvent
        - [x] MusicEvent
        - [x] PublicationEvent
            - [x] BroadcastEvent
            - [x] OnDemandEvent
        - [x] SaleEvent
        - [x] ScreeningEvent
        - [x] SocialEvent
        - [x] SportsEvent
        - [x] TheaterEvent
        - [x] VisualArtsEvent
    - [x] Intangible
        - [x] AlignmentObject
        - [x] Audience
            - [x] BusinessAudience
            - [x] EducationalAudience
            - [x] PeopleAudience
                - [x] ParentAudience
        - [x] BedDetails
        - [x] Brand
        - [x] BroadcastChannel
            - [x] RadioChannel
            - [x] TelevisionChannel
        - [x] BusTrip
        - [x] ComputerLanguage
        - [x] DataFeedItem
        - [x] Demand
        - [x] DigitalDocumentPermission
        - [x] EntryPoint
        - [x] Enumeration
            - [x] ActionStatusType
            - [x] BoardingPolicyType
            - [x] BookFormatType
            - [x] BusinessEntityType
            - [x] BusinessFunction
            - [x] ContactPointOption
            - [x] DayOfWeek
            - [x] DeliveryMethod
                - [x] LockerDelivery
                - [x] ParcelService
            - [x] DigitalDocumentPermissionType
            - [x] EventStatusType
            - [x] GamePlayMode
            - [x] GameServerStatus
            - [x] GenderType
            - [x] ItemAvailability
            - [x] ItemListOrderType
            - [x] MapCategoryType
            - [x] MusicAlbumProductionType
            - [x] MusicAlbumReleaseType
            - [x] MusicReleaseFormatType
            - [x] OfferItemCondition
            - [x] OrderStatus
            - [x] PaymentMethod
                - [x] PaymentCard
                    - [x] CreditCard
            - [x] PaymentStatusType
            - [x] QualitativeValue
                - [x] DriveWheelConfigurationValue
                - [x] SteeringPositionValue
            - [x] ReservationStatusType
            - [x] RestrictedDiet
            - [x] RsvpResponseType
            - [x] Specialty
            - [x] WarrantyScope
        - [x] Flight
        - [x] GameServer
        - [x] Invoice
        - [x] ItemList
            - [x] BreadcrumbList
            - [x] OfferCatalog
        - [x] JobPosting
        - [x] Language
        - [x] ListItem
        - [x] Offer
            - [x] AggregateOffer
        - [x] Order
        - [x] OrderItem
        - [x] ParcelDelivery
        - [x] Permit
            - [x] GovernmentPermit
        - [x] ProgramMembership
        - [x] PropertyValueSpecification
        - [x] Quantity
            - [x] Distance
            - [x] Duration
            - [x] Energy
            - [x] Mass
        - [x] Rating
            - [x] AggregateRating
        - [x] Reservation
            - [x] BusReservation
            - [x] EventReservation
            - [x] FlightReservation
            - [x] FoodEstablishmentReservation
            - [x] LodgingReservation
            - [x] RentalCarReservation
            - [x] ReservationPackage
            - [x] TaxiReservation
            - [x] TrainReservation
        - [x] Role
            - [x] OrganizationRole
                - [x] EmployeeRole
            - [x] PerformanceRole
        - [x] Seat
        - [x] Service
            - [x] BroadcastService
            - [x] CableOrSatelliteService
            - [x] FinancialProduct
                - [x] BankAccount
                    - [x] DepositAccount
                - [x] CurrencyConversionService
                - [x] InvestmentOrDeposit
                    - [x] DepositAccount
                - [x] LoanOrCredit
                    - [x] CreditCard
                - [x] PaymentCard
                - [x] PaymentService
            - [x] FoodService
            - [x] GovernmentService
            - [x] TaxiService
        - [x] ServiceChannel
        - [x] StructuredValue
            - [x] ContactPoint
                - [x] PostalAddress
            - [x] EngineSpecification
            - [x] GeoCoordinates
            - [x] GeoShape
                - [x] GeoCircle
            - [x] InteractionCounter
            - [x] MonetaryAmount
            - [x] NutritionInformation
            - [x] OpeningHoursSpecification
            - [x] OwnershipInfo
            - [x] PriceSpecification
                - [x] CompoundPriceSpecification
                - [x] DeliveryChargeSpecification
                - [x] PaymentChargeSpecification
                - [x] UnitPriceSpecification
            - [x] PropertyValue
                - [x] LocationFeatureSpecification
            - [x] QuantitativeValue
            - [x] TypeAndQuantityNode
            - [x] WarrantyPromise
        - [x] Ticket
        - [x] TrainTrip
    - [x] Organization
        - [x] Airline
        - [x] Corporation
        - [x] EducationalOrganization
            - [x] CollegeOrUniversity
            - [x] ElementarySchool
            - [x] HighSchool
            - [x] MiddleSchool
            - [x] Preschool
            - [x] School
        - [x] GovernmentOrganization
        - [x] LocalBusiness
            - [x] AnimalShelter
            - [x] AutomotiveBusiness
                - [x] AutoBodyShop
                - [x] AutoDealer
                - [x] AutoPartsStore
                - [x] AutoRental
                - [x] AutoRepair
                - [x] AutoWash
                - [x] GasStation
                - [x] MotorcycleDealer
                - [x] MotorcycleRepair
            - [x] ChildCare
            - [x] Dentist
            - [x] DryCleaningOrLaundry
            - [x] EmergencyService
                - [x] FireStation
                - [x] Hospital
                - [x] PoliceStation
            - [x] EmploymentAgency
            - [x] EntertainmentBusiness
                - [x] AdultEntertainment
                - [x] AmusementPark
                - [x] ArtGallery
                - [x] Casino
                - [x] ComedyClub
                - [x] MovieTheater
                - [x] NightClub
            - [x] FinancialService
                - [x] AccountingService
                - [x] AutomatedTeller
                - [x] BankOrCreditUnion
                - [x] InsuranceAgency
            - [x] FoodEstablishment
                - [x] Bakery
                - [x] BarOrPub
                - [x] Brewery
                - [x] CafeOrCoffeeShop
                - [x] FastFoodRestaurant
                - [x] IceCreamShop
                - [x] Restaurant
                - [x] Winery
            - [x] GovernmentOffice
                - [x] PostOffice
            - [x] HealthAndBeautyBusiness
                - [x] BeautySalon
                - [x] DaySpa
                - [x] HairSalon
                - [x] HealthClub
                - [x] NailSalon
                - [x] TattooParlor
            - [x] HomeAndConstructionBusiness
                - [x] Electrician
                - [x] GeneralContractor
                - [x] HVACBusiness
                - [x] HousePainter
                - [x] Locksmith
                - [x] MovingCompany
                - [x] Plumber
                - [x] RoofingContractor
            - [x] InternetCafe
            - [x] LegalService
                - [x] Attorney
                - [x] Notary
            - [x] Library
            - [x] LodgingBusiness
                - [x] BedAndBreakfast
                - [x] Campground
                - [x] Hostel
                - [x] Hotel
                - [x] Motel
                - [x] Resort
            - [x] MedicalBusiness(https://health-lifesci.schema.org/MedicalBusiness "Extended schema: health-lifesci.schema.org")
                - [x] Dentist
                - [x] Pharmacy
                - [x] Physician
            - [x] ProfessionalService
            - [x] RadioStation
            - [x] RealEstateAgent
            - [x] RecyclingCenter
            - [x] SelfStorage
            - [x] ShoppingCenter
            - [x] SportsActivityLocation
                - [x] BowlingAlley
                - [x] ExerciseGym
                - [x] GolfCourse
                - [x] HealthClub
                - [x] PublicSwimmingPool
                - [x] SkiResort
                - [x] SportsClub
                - [x] StadiumOrArena
                - [x] TennisComplex
            - [x] Store
                - [x] AutoPartsStore
                - [x] BikeStore
                - [x] BookStore
                - [x] ClothingStore
                - [x] ComputerStore
                - [x] ConvenienceStore
                - [x] DepartmentStore
                - [x] ElectronicsStore
                - [x] Florist
                - [x] FurnitureStore
                - [x] GardenStore
                - [x] GroceryStore
                - [x] HardwareStore
                - [x] HobbyShop
                - [x] HomeGoodsStore
                - [x] JewelryStore
                - [x] LiquorStore
                - [x] MensClothingStore
                - [x] MobilePhoneStore
                - [x] MovieRentalStore
                - [x] MusicStore
                - [x] OfficeEquipmentStore
                - [x] OutletStore
                - [x] PawnShop
                - [x] PetStore
                - [x] ShoeStore
                - [x] SportingGoodsStore
                - [x] TireShop
                - [x] ToyStore
                - [x] WholesaleStore
            - [x] TelevisionStation
            - [x] TouristInformationCenter
            - [x] TravelAgency
        - [x] MedicalOrganization
            - [x] Dentist
            - [x] Hospital
            - [x] Pharmacy
            - [x] Physician
        - [x] NGO
        - [x] PerformingGroup
            - [x] DanceGroup
            - [x] MusicGroup
            - [x] TheaterGroup
        - [x] SportsOrganization
            - [x] SportsTeam
    - [x] Person
    - [x] Place
        - [x] Accommodation
            - [x] Apartment
            - [x] CampingPitch
            - [x] House
                - [x] SingleFamilyResidence
            - [x] Room
                - [x] HotelRoom
                - [x] MeetingRoom
            - [x] Suite
        - [x] AdministrativeArea
            - [x] City
            - [x] Country
            - [x] State
        - [x] CivicStructure
            - [x] Airport
            - [x] Aquarium
            - [x] Beach
            - [x] Bridge
            - [x] BusStation
            - [x] BusStop
            - [x] Campground
            - [x] Cemetery
            - [x] Crematorium
            - [x] EventVenue
            - [x] FireStation
            - [x] GovernmentBuilding
                - [x] CityHall
                - [x] Courthouse
                - [x] DefenceEstablishment
                - [x] Embassy
                - [x] LegislativeBuilding
            - [x] Hospital
            - [x] MovieTheater
            - [x] Museum
            - [x] MusicVenue
            - [x] Park
            - [x] ParkingFacility
            - [x] PerformingArtsTheater
            - [x] PlaceOfWorship
                - [x] BuddhistTemple
                - [x] CatholicChurch
                - [x] Church
                - [x] HinduTemple
                - [x] Mosque
                - [x] Synagogue
            - [x] Playground
            - [x] PoliceStation
            - [x] RVPark
            - [x] StadiumOrArena
            - [x] SubwayStation
            - [x] TaxiStand
            - [x] TrainStation
            - [x] Zoo
        - [x] Landform
            - [x] BodyOfWater
                - [x] Canal
                - [x] LakeBodyOfWater
                - [x] OceanBodyOfWater
                - [x] Pond
                - [x] Reservoir
                - [x] RiverBodyOfWater
                - [x] SeaBodyOfWater
                - [x] Waterfall
            - [x] Continent
            - [x] Mountain
            - [x] Volcano
        - [x] LandmarksOrHistoricalBuildings
        - [x] LocalBusiness
        - [x] Residence
            - [x] ApartmentComplex
            - [x] GatedResidenceCommunity
        - [x] TouristAttraction
    - [x] Product
        - [x] IndividualProduct
        - [x] ProductModel
        - [x] SomeProducts
        - [x] Vehicle
            - [x] Car

**Comment by sebastiandedeyne** [comment]
Didn't expect to actually be able to close this 😅

**Comment by freekmurze** [comment]
Haha, epic issue!
