### ISSUE TITLE
Datetime values throws InvalidProperty exceptions

### ISSUE THREAD

**Issue by oscarotero** [spatie/schema-org#10]
Hi!
Thanks for this great library. I'm using it to generate the schema of some articles and I get an exception using `Datetime` instances as the value of some properties like `dateCreated`. Example:

```php
use Spatie\SchemaOrg\Schema;

$schema = Schema::Article()
	->headLine($article->title)
	->author(Schema::Person()
		->name($article->author->name)
	)
	->dateCreated(new Datetime($article->createdDate));

echo $schema->toScript();
```

[The signature of the function](https://github.com/spatie/schema-org/blob/master/src/CreativeWork.php#L374) accepts `DateTimeInterface` instances, so in theory this should work.

**Comment by derhasi** [comment]
The current `@param` documentation seems not be accurate there at the moment. I had to convert the datetime to _ISO 8601_ (e.g. `$data->format('c')` or `data('c', $timestamp)) as a workaround.

**Comment by sebastiandedeyne** [comment]
Sorry @oscarotero, totally missed this issue!

Tagged a new release that wil format objects that implement `DateTimeInterface` to ISO 8601 as per the spec.

https://github.com/spatie/schema-org/releases/tag/1.2.0

**Comment by oscarotero** [comment]
Great. Thank you!
