### ISSUE TITLE
Method to change type of a schema to a more specific type

### ISSUE THREAD

**Issue by architchandra** [spatie/schema-org#103]
I may have missed out on something as I'm new to both structured data and this package (which I use through https://github.com/vaersaagod/seomate), but is there a method that could convert an existing schema type to a more specific version of that type?

eg. Change `Organization` to `EducationalOrganization` or `WebPage` to `FAQPage`

Please let me know.
Thank you.

**Comment by Gummibeer** [comment]
Hey,

I don't know why you want to do this but in general you can pass all properties to the new type via `addProperties()`.

**Comment by architchandra** [comment]
I have added a `WebPage` schema to a base template that I use to extend other specific templates. I use the `WebPage` as the `mainEntityOfPage` but in certain cases like when the page is related to FAQs, I would like to have the ability to convert that `WebPage` schema already included through the parent to the more particular `FAQPage`. 

Please bear with me if you think I'm doing something wrong. I'm very new to using custom structured data and to Craft CMS and Twig, which I am using to implement this.

**Comment by Gummibeer** [comment]
What would you expect a `makeFromType()` method to do? Should it only wrap the current approach? Or should it only apply the properties both types have in common to prevent invalid schema?
