### ISSUE TITLE
Errors with old style autoloading in legacy projects

### ISSUE THREAD

**Issue by PiotrWochna** [spatie/schema-org#107]
Hello,

when using old style autoloaders in legacy projects Schema generating fails - reason: autoload fail. The problem lies in method_exists search from __toString method. method_exists() triggers autoload. In modern application based on composer autoload it is no problem. But in legacy projects with custom autoloaders it is huge problem.

Sample example:
```php
<?php
use Spatie\SchemaOrg\Schema;

require_once './../vendor/autoload.php';

spl_autoload_register(function ($class) {

   require $class.'.php';

});

$localBusiness = Schema::localBusiness()->name('Spatie');

print_r($localBusiness->toArray());
```

```
Warning: require(Spatie.php): failed to open stream: No such file or directory
```

I understand that this autoloader is rather stupid example, but it shows the problem. This worked fine in version 2.0.* - method_exists was used only for objects (https://github.com/spatie/schema-org/blob/2.0.3/src/BaseType.php#L105)

The other solution would be to simple return string values at beginning. All those matches for interfaces for string are waste of time.

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/2.10.0
