### ISSUE TITLE
Create property 'query-input' based on Google's requirements

### ISSUE THREAD

**Issue by architchandra** [spatie/schema-org#110]
In its list of supported structured data types, Google also mentions `Sitelinks Searchbox`: https://developers.google.com/search/docs/data-types/sitelinks-searchbox

Here, they use a modified `SearchAction` schema type and have added a `query-input` property. It would be great if this can be added.

Thanks.

**Comment by Gummibeer** [comment]
Hey,
we only support the schema.org as is defined in https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa
But you can add custom properties by calling `setProperty()` directly.
https://github.com/spatie/schema-org#advanced-usage

**Comment by architchandra** [comment]
Thanks. I'll try this.

**Comment by ecoplace** [comment]
I managed to implement it using the following code if it helps anyone in the future,

$grapgh->potentialAction(
            \Spatie\SchemaOrg\Schema::searchAction()
            ->target((new Spatie\SchemaOrg\EntryPoint)->urlTemplate('https://www.domain.com?q={search_term_string}'))
            ->setProperty('query-input',['type'=>'PropertyValueSpecification','valueRequired'=>true,'valueName'=>'search_term_string']))

**Comment by paulofreitas** [comment]
By the way this is defined on [Potential Actions schema, Part 4: Input and Output constraints](https://schema.org/docs/actions.html#part-4) but unfortunately it's not defined on `schemaorg/data/schema.ttl`.

For anyone wanting to implement this, you can do it that way:

```php
$graph
    // ...
    ->potentialAction(
        Schema::searchAction()
            ->target(
                Schema::entryPoint()
                    ->urlTemplate(url('/?q={search_term_string}'))
            )
            ->setProperty(
                'query-input',
                Schema::propertyValueSpecification()
                    ->valueRequired(true)
                    ->valueName('search_term_string')
            )
    );
 ```
