### ISSUE TITLE
TouristDestination missing

### ISSUE THREAD

**Issue by arunspl** [spatie/schema-org#125]
https://schema.org/TouristDestination

**Comment by Gummibeer** [comment]
Hey,
this is a *pending* type - so we can't add it via the generator.

> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.

> The code in src is generated from Schema.org's RDFa standards file, so it provides objects and methods for the entire core vocabulary. 

So you can add it your own by hand and extend the base type or wait until it's in the official release.
If you can find any official RDFa file for pending types I would be happy to add them in beta releases.
