### ISSUE TITLE
MedicalWebPage missing type 

### ISSUE THREAD

**Issue by Samadu61** [spatie/schema-org#126]
https://schema.org/MedicalWebPage

**Comment by Gummibeer** [comment]
Hey,
even if the schema isn't marked as pending it seems like it's not present in the latest RDFa file
https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa
I've run the generator and there are some changes, which I will release today, but the requested type isn't part of it.
Following the readme we don't create types/schemas ourself:
> The code in `src` is generated from Schema.org's RDFa standards file
