### ISSUE TITLE
Schema v7.0

### ISSUE THREAD

**Issue by satoved** [spatie/schema-org#129]
New Schema.org version released with new types https://schema.org/docs/releases.html#v7.0

Many concern Event type to address postponed events due to the virus.

**Comment by Gummibeer** [comment]
Hey,
thanks for reporting - but right now the RDFa file isn't updated. So we can't update this package.

**Comment by marcwieland95** [comment]
Is it solvable now?

**Comment by poldixd** [comment]
I had the same problem. I needed the _new_ propertiy`VirtualLocation` (https://developers.google.com/search/docs/data-types/event).

Here is my _dirty_ workaround for 2.12.1:

``` php
Schema::theaterEvent()
    ->name('Foo Bar')
    ->eventAttendanceMode('https://schema.org/OnlineEventAttendanceMode')
    ->addProperties([
        'name' => 'value', 
        'location' => [
            '@type' => 'VirtualLocation',
            'name' => 'Foo Bar!!!',
            'description' => 'Foo Bar???',
            'url' => 'https://foo.bar',
        ]
    ]);
```

**Comment by Gummibeer** [comment]
@poldixd it would be cleaner if you add a new class like the generated ones.
Right now the `VirtualLocation` is pending.
https://schema.org/VirtualLocation
> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.

**Comment by Gummibeer** [comment]
I've generated the types by the current RDFa - but only some methods were added. The v7 still seems not added to it.
https://github.com/spatie/schema-org/releases/tag/2.13.0

**Comment by marcwieland95** [comment]
@Gummibeer Thanks for the release.
The solution of @poldixd works for now. But I'm happy to replace with the proper `VirtualLocation` as soon as the RFDa is up to date.

**Comment by Gummibeer** [comment]
@marcwieland95 yeah, the package itself is super extendable. It only requires one interface or basic values to work.
We will try to release as soon as possible. I try to get a GitHub Action together that will notify us if the RDFa has changed. Auto-Release is dangerous because the RDFa doesn't contain a version it corresponds to - so the RDFa and therefor this package are more floating releases. Which isn't always easy to handle because it's sometimes hard to decide how to release a new version.

**Comment by Gummibeer** [comment]
Hey,

we are on `v7.04` now since schema.org uses a releases folder in the GitHub repo.

**Comment by marcwieland95** [comment]
Great. Thanks for your work
