### ISSUE TITLE
Instantiate classes with array of properties 

### ISSUE THREAD

**Issue by LunarDevelopment** [spatie/schema-org#131]
Either I'm missing it or it doesn't exist; it'd be nice to instantiate the classes with an array or properties which are then mapped to the class properties, for example: 

```php
$brand = Schema::Brand([
            'name' => "The name of this brand",
            'slogan' => "All the branding all the time.",
            'description' => "We're not the best brand but by god we get results.",
        ]);
```
or..
```php
$brand = new Graph();
        $brand->brand([
            'name' => "The name of this brand",
            'slogan' => "All the branding all the time.",
            'description' => "We're not the best brand but by god we get results.",
        ]);
```

**Comment by Gummibeer** [comment]
Hey, not for instantiation but a method that allows what you want is the `addProperties()`.
https://github.com/spatie/schema-org/blob/a549c478c8c7743084d18e921edee60a14083aef/src/BaseType.php#L36-L43

This method does exactly what you wanted. And because it's chainable I would say that this should solve your issue!?

**Comment by LunarDevelopment** [comment]
Fantastic, thanks for this! 

I wonder if you could let me know if there's an easy way to push to array, for example some kind of loop code that pushed reviews to the schema without adding them to a local array first? 

```php 
$localBusiness = Schema::localBusiness()
            ->reviews(
                Schema::review()
                    ->url($var)
                    ->reviewRating($var)
                    ->author($var))
            ->reviews(
                Schema::review()
                    ->url($var)
                    ->reviewRating($var)
                    ->author($var)
            )
```

**Comment by Gummibeer** [comment]
Hey,
because your data will be somewhere in any variable!? You could use `array_map()` to convert it to an array of schema types.
But there's no method to push something to a schema property.
So you will need to build the array in any way your own and assign it to the property.

**Comment by LunarDevelopment** [comment]
Okay I understand, 

Thank you for all your help and great work!
