### ISSUE TITLE
How do you fill a mainEntity array?

### ISSUE THREAD

**Issue by notflip** [spatie/schema-org#132]
I'm following the example for an faq page: https://developers.google.com/search/docs/data-types/faqpage

The mainEntity here is an array with multiple definitions, How can I achieve this using the mainEntity function on the faqPage, in short how can I work with array data?

```
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [{
        "@type": "Question",
        "name": "What is the return policy?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "answer"
        }
      }, {
        "@type": "Question",
        "name": "How long does it take to process a refund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "answer"
        }
      }
```

**Comment by Gummibeer** [comment]
Hey,

"every" method allows to pass in eg `string` and `string[]`.
So in your case you could do:

```php
Schema:: fAQPage()
  ->mainEntity([
    Schema::question(),
    Schema::question(),
    $questionWrittenIntoVar,
  ])
```

https://github.com/spatie/schema-org/blob/a549c478c8c7743084d18e921edee60a14083aef/src/FAQPage.php#L1017-L1030

**Comment by notflip** [comment]
Perfect, thank you!
