### ISSUE TITLE
do this package have same of types ?

### ISSUE THREAD

**Issue by vahidalvandi** [spatie/schema-org#138]
hey
i need  
   "@type": "Question"
type do this package support it ? or rank a page ,... ?

**Comment by Gummibeer** [comment]
Hey,

just check out the [Schema factory](https://github.com/spatie/schema-org/blob/master/src/Schema.php) it contains a method for every type.

The question type is available at
https://github.com/spatie/schema-org/blob/419f3703015e86f2daccc63649c070e7bb5c52b3/src/Question.php
