### ISSUE TITLE
Scrutinizer causing slow confirmation of PR tests

### ISSUE THREAD

**Issue by mallardduck** [spatie/schema-org#142]
This repo has slow confirmation times for PRs which are seemingly successfully.

Looking further into the issue I found that Scrutinizer was the cause of the hangup. Reviewing ScrutinizerCI shows that the tests have been silently failing to receive the remote code coverage.

From what I see in an older spot of the repo is that TravisCI was setup to send those coverage reports. These reports are not being sent by Github and it seems due to those configs lacking the proper script call.

Proposed Fixes:

- Send coverage from GitHub to Scrutinizer
- Disable external code coverage for Scrutinizer

**Comment by Gummibeer** [comment]
My go-to would be disabling external code coverage or even scrutinizer at all.
Never had a single benefit of it.

At the end: even if scrutinizer fails but all other tests pass and I approve the changes I will merge it. I really don't care about it. 😅
But I believe that removing the config wasn't enough but @freekmurze would have to disable it on the scrutinizer platform itself.

Will ask him today to do so. 😊

**Comment by freekmurze** [comment]
Done.
