### ISSUE TITLE
Allow multiple types

### ISSUE THREAD

**Issue by michretz** [spatie/schema-org#147]
schema.org now allows multiple types (@type).
i can set multiple types by setProperty("@type", $typeList), but i only get the initialized Type by the Classname
this is defined in the function "getType" in the class "BaseType".
if there would be a check for defined "@type", multiple types would be possible

    public function getType()
    {
        if (empty($this->properties["@type"])) {
            return (new ReflectionClass($this))->getShortName();
        }

        return $this->properties["@type"];
    }

**Comment by Gummibeer** [comment]
Hey,

could you add a link of the release that added multiple type support and also what a usecase could be? 🤔
I would add an official release supporting a native way to do so if you can link me to some resources?

**Comment by michretz** [comment]
https://github.com/schemaorg/schemaorg/wiki/How-to-use-Multi-Typed-Entities-or-MTEs

**Comment by Gummibeer** [comment]
Hey,

thanks for the link - just an idea, don't know if that would be really useful for you as I don't use MTEs.

```php
$mte = new MTE();

$mte->product()->...;
$mte->sushi()->...;

$mte->toScript();
```

```html
<script>{"@type": ["Product", "Sushi"], ...}</script>
```

Behind the scenes the MTE would work similar to the `Graph` https://github.com/spatie/schema-org#graph---multiple-items - it's a collection of Types but on serialize it will render all types as array in `@type` and merge all properties.
The benefit I would see is still fully working autocomplete support for all the methods/properties.

**Comment by michretz** [comment]
sounds good to me.

**Comment by Gummibeer** [comment]
I'm on it and everything looks good in first try.
But have to leave office now, so I think that I will finish it Monday or later next week. 🎉

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/3.1.0
