### ISSUE TITLE
Suggestion: Avoid empty strings in properties

### ISSUE THREAD

**Issue by jose-gomez-evinex** [spatie/schema-org#151]
I know this coudl be done before the setProperty function but sometimes properties are set from external functions and it could be very handy.

Currently if I try to set a property = NULL this is not set. 
It would be awesome if the same happened if I try to set an empty string.

Does it make sense to have a property with an empty string as value in Schema? (I'm asking, maybe I'm missing something).

This could be added in src/BasyType.php (line 27)

```
   public function setProperty(string $property, $value)
    {
        if ($value !== null) {
            $this->properties[$property] = $value;
        }

        return $this;
    }
```

Resultin in:

```
   public function setProperty(string $property, $value)
    {
        if ($value !== null && $value != '') {
            $this->properties[$property] = $value;
        }

        return $this;
    }
```

**Comment by Gummibeer** [comment]
Hey,

I also don't know/see a reason why you should use an empty string as a value.
But in general you should more likely use the `if()` method if you don't know that the dynamic content is always a valid value. 🤔

If you want to provide a PR I will very likely merge it as II can't imagine a case that this would break. But I won't implement it myself.
