### ISSUE TITLE
Type Product is adding `@id` instead of `identification`

### ISSUE THREAD

**Issue by JohJohan** [spatie/schema-org#156]
When generating Product with an id it will generate a `@id` instead of `identification`. https://schema.org/Product shows https://schema.org/identifier

This was probably introduced by https://github.com/spatie/schema-org/pull/102

**Comment by Gummibeer** [comment]
> The identifier property and its sub-properties are primarily useful in cases where the content is expressed as a textual string. Increasingly there are canonical URL/URI representations for each of these. All schema.org syntaxes already have built-in representation for URIs and URLs, e.g. in Microdata 'itemid', in RDFa 1.1, 'resource', in JSON-LD, '@id'. Generally it is preferable to use these unless there is a specific requirement to explicitly state the kind of identifier, or to provide additional / alternative identifiers (e.g., DOIs). Such requirements are common e.g. for scientific dataset description.

After reading it again I think that a middle solution would be right.
`@id` is the correct key for simple string identifiers but typed identifiers should remain `identifier`.
I won't work on this until mid January. But I would welcome a PR that fixes this.

I wish you a merry Christmas! ⛄🎄🦌

**Comment by JohJohan** [comment]
Okay i would like to pick this up. I have an idea to create a interface class `TypedIdentifierInterface` that way i can check if i need to add `@id` or `identifier` is that a okay solution? And is there a way for me to find out what are simple string identifiers and what are tped identifiers?

**Comment by Gummibeer** [comment]
Hey,
we already have everything - only the snippet that replaces the `identifier` with `@id` has to be conditional.
https://github.com/spatie/schema-org/blob/3b22822c19b1c6e4a889ea7af3b8cc76ca8fc622/generator/templates/static/BaseType.php#L129-L135

It should check if `$this['identifier']` is a `string` or an object - you could check for `Type` interface.
Following the schema.org docs you can use an URL (which is `string`) or text or an instance of `PropertyValue` which we already have as an available type.
https://github.com/spatie/schema-org/blob/master/src/PropertyValue.php

**Comment by JohJohan** [comment]
Hello @Gummibeer,

Thank you for helping out. I managed to make a pull request https://github.com/spatie/schema-org/pull/157.

Let me know if i missed something.
