### ISSUE TITLE
PHP 5.6 support?

### ISSUE THREAD

**Issue by lu3do** [spatie/schema-org#16]
Any reason why the requirement is php 7?

**Comment by freekmurze** [comment]
In this package scalar type hints, return type hints and the null coalescence operator are used.

If you need a PHP 5 compatible version just fork the package and maintain your own version.

**Comment by derhasi** [comment]
I created a fork for that, as we will not be able to use PHP7 on the production server: https://github.com/derhasi/schema-org

I used _spatie/7to5_ for some parts. Great tool. 💙
