### ISSUE TITLE
Composer autoloader throws 'Fatal error: Uncaught Error: Class 'LocalBusiness' not found'

### ISSUE THREAD

**Issue by joepdooper** [spatie/schema-org#161]
Great work first of all!

With the composer autoloader (vendor/autoload.php) or with my own `spl_autoload_register()` I get `Fatal error: Uncaught Error: Class 'LocalBusiness' not found …` when using the following code:

```php
$localBusiness = new LocalBusiness();
$localBusiness->name('Spatie');
print $localBusiness->toScript(); 
```

With my own `spl_autoload_register()` it even loads the files needed but throws this `Fatal error` anyway.

Other classes, for instance from [Mollie](https://github.com/mollie/mollie-api-php) or [htmlpurifier](https://github.com/ezyang/htmlpurifier), load perfectly fine with the composer autoloader. I am not sure if I am doing something wrong…

**Comment by boospot** [comment]
Looks like a namespace issue.
Have you included the Namespace at the top of php file where you are intatiating this class?

it should look something like thie:

`use Spatie\SchemaOrg\LocalBusiness;`

or, try to use:

`$localBusiness = new Spatie\SchemaOrg\LocalBusiness;`

**Comment by joepdooper** [comment]
Ah yes, sorry! Thanks a lot! Stupid me…
