### ISSUE TITLE
Recipe properties missing

### ISSUE THREAD

**Issue by derhasi** [spatie/schema-org#17]
The current schema.org documentation on https://schema.org/Recipe says that Recipe should have properties like _prepTime_, _recipeIngredient_, _recipeInstructions_, _recipeYield_ and so on. They currently aren't generated in [Recipe.php](https://github.com/spatie/schema-org/blob/master/src/Recipe.php).

The [source](https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-callisto/data/schema.rdfa) does hold some information about these fields though:

```html
<div typeof="rdf:Property" resource="http://schema.org/recipeYield">
  <span class="h" property="rdfs:label">recipeYield</span>
  <span property="rdfs:comment">The quantity produced by the recipe (for example, number of people served, number of servings, etc).</span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Recipe"> Recipe</a></span>
  <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text"> Text </a></span>
</div>
```

**Comment by sebastiandedeyne** [comment]
Looks like the properties wouldn't get included if it wasn't an *exact* match. Note how `Recipe` has a leading space in the rdfa here:

```
<span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Recipe"> Recipe</a></span>
```

Thanks for the heads up, tagged a new version that fixes this issue!

https://github.com/spatie/schema-org/releases/tag/1.2.0
