### ISSUE TITLE
`MediaObject` (and others) should allow `string`-value for `duration`

### ISSUE THREAD

**Issue by jaylinski** [spatie/schema-org#172]
According to the spec, instances of `Duration` may appear as a value (`string`) for the following properties specified on this page:

https://schema.org/Duration

But right now, it is required to always use the `DurationContract`:

https://github.com/spatie/schema-org/blob/e092f59d5556ccada9e0c178b12bf1626e26cbbc/src/MediaObject.php#L816-L829

To my understanding, the PHP doc should be changed to allow `string`:

```
@param string|\Spatie\SchemaOrg\Contracts\DurationContract|\Spatie\SchemaOrg\Contracts\DurationContract[] $duration
```

This is also true for all children of `MediaObject`, like `VideoObject`.

I'm not sure how this can be implemented using the generator though...

**Comment by Gummibeer** [comment]
This should be changed in the original Schema.org's JSON-LD standards file.
https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/13.0/schemaorg-all-https.jsonld

**Comment by jaylinski** [comment]
@Gummibeer As far as I can tell the schema is correct, or am I missing something?

### `duration` as property

```
    {
      "@id": "schema:duration",
      "@type": "rdf:Property",
      "rdfs:comment": "The duration of the item (movie, audio recording, event, etc.) in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601).",
      "rdfs:label": "duration",
      "schema:domainIncludes": [
        {
          "@id": "schema:Episode"
        },
        {
          "@id": "schema:Schedule"
        },
        {
          "@id": "schema:MediaObject"
        },
        {
          "@id": "schema:Event"
        },
        {
          "@id": "schema:QuantitativeValueDistribution"
        },
        {
          "@id": "schema:MusicRecording"
        },
        {
          "@id": "schema:Movie"
        },
        {
          "@id": "schema:MusicRelease"
        },
        {
          "@id": "schema:Audiobook"
        }
      ],
      "schema:rangeIncludes": {
        "@id": "schema:Duration"
      },
      "schema:source": [
        {
          "@id": "https://github.com/schemaorg/schemaorg/issues/1698"
        },
        {
          "@id": "https://github.com/schemaorg/schemaorg/issues/1457"
        }
      ]
    },
```

### `Duration` as class

```
    {
      "@id": "schema:Duration",
      "@type": "rdfs:Class",
      "rdfs:comment": "Quantity: Duration (use [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601)).",
      "rdfs:label": "Duration",
      "rdfs:subClassOf": {
        "@id": "schema:Quantity"
      }
    },
```

**Comment by Gummibeer** [comment]
```
"schema:rangeIncludes": {
      "@id": "schema:Duration"
},
```

Haven't fully checked our generator - but nothing in there says that you can pass in a string directly. Okay, you can, only your analyzer will complain. But regarding the spec it clearly says that it expects a `schema:Duration`.

**Comment by jaylinski** [comment]
Ah, I think I get it now, it should be

```
      "schema:rangeIncludes": [
        {
          "@id": "schema:Duration"
        },
        {
          "@id": "schema:Text"
        }
      ],
```

That would generate the correct classes?

I'll test this with a local fixed copy and will open a PR in the main repository.

**Comment by Gummibeer** [comment]
something like that - yes.
