### ISSUE TITLE
Graph node type transformation

### ISSUE THREAD

**Issue by milosevicn** [spatie/schema-org#173]
Hi,

Is it possible to change type of graph node after I create it? For example, I have created `article` node:

```
...
$graph->article()
            ->identifier($graph->webPage()['url'].'#/schema/article/'.$entity['id'])
            ->headline($entity['title'])
            ->description($entity['meta_description'])
            ->inLanguage('en-Us')
            ->isPartOf($graph->webPage()->referenced()->toArray())
            ->mainEntityOfPage($graph->webPage()->referenced()->toArray())
            ->datePublished($entity['created_at'])
            ->dateModified($entity['updated_at'])
            ->author($graph->person()->referenced()->toArray())
            ->publisher($graph->organization()->referenced()->toArray());
```

Now I want to change it from `Article` to `NewsArticle`, but I am not sure how can I do it, if I haven't initially defined it using `->newsArticle()`. Can I explicitly do it like this `$graph->article()['@type'] = ['Article', 'NewsArticle'];`?

**Comment by Gummibeer** [comment]
Hey,
the only way would be to have a transformer copying all properties from `article` to `newsArticle` object. After that removing the old article and adding the new news article. This would remove all relations.

**Comment by milosevicn** [comment]
Understood, there isn't single function to do it. Thanks, you can close the issue

**Comment by Gummibeer** [comment]
If you could provide a general `transformTo(string $type)` method that handles all this I would be happy to merge it.
as we have thousands of interfaces this could be possible with some reflection/implements or similar magic.

**Comment by milosevicn** [comment]
I'll try, but I need some time
