### ISSUE TITLE
Rendering above <html>

### ISSUE THREAD

**Issue by AlignConnect** [spatie/schema-org#175]
![image](https://user-images.githubusercontent.com/68729388/146001959-4195d259-8f2f-4721-bfda-9eb489c6a824.png)

echo $schema->toScript();

I followed the documentation and found that script is rendering above `<html>`. 

Is there a way to render it in `<head>` ?

**Comment by Jubeki** [comment]
Don't echo in the Controller. Echo in the head part.

```php
class HomepageController
{

    public function show()
    {
          // Don't echo here
    }

}

```

```html
<html>

<head>
     {{ echo $schema->toScript() }}
</head>
<body>

</body>
</html>
```
