### ISSUE TITLE
additional vocabularies

### ISSUE THREAD

**Issue by halmos** [spatie/schema-org#177]
Is it possible to add additional vocabularies to the @context? I understand this library is intended for use with schema.org, but in the case where we may need to add additional vocabulary terms that don't exist in schema.org, it might be a useful feature.

**Comment by Gummibeer** [comment]
You can create as many custom types as you want to.

**Comment by halmos** [comment]
Thank you, but how do I add the additional vocabulary to the `@context` field? 

Should it be something like this?

```php
Schema::context(["https:\/\/schema.org", ["nc" => "http://release.niem.gov/niem/niem-core/4.0/#"}]);
```

**Comment by Gummibeer** [comment]
The `BaseType` allows you to return your own context for the type.
https://github.com/spatie/schema-org/blob/2adeec32d1afb4aaf3299eccb9aa151b1b98868b/src/BaseType.php#L17-L20
