### ISSUE TITLE
Notices in PHP8.1

### ISSUE THREAD

**Issue by boehmDa** [spatie/schema-org#178]
When using the code on PHP8.1.2, the following notices will show up:

> Return type of Spatie\SchemaOrg\BaseType::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> Return type of Spatie\SchemaOrg\BaseType::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> Return type of Spatie\SchemaOrg\BaseType::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> Return type of Spatie\SchemaOrg\BaseType::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> Return type of Spatie\SchemaOrg\BaseType::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by Gummibeer** [comment]
#174

**Comment by pguillard** [comment]
trying to re-open this issue, beacause it relates to PHP 8 compatibility !!
