### ISSUE TITLE
When using the code on PHP8.1, the following notices will show up:

### ISSUE THREAD

**Issue by pguillard** [spatie/schema-org#183]
On  spatie/schema-org:^3.4
Deprecated function : Return type of Spatie\SchemaOrg\BaseType::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice dans include() (/project/vendor/spatie/schema-org/src/BaseType.php ligne 12)

As I could not re-open issue #178 , lets try a new one.

**Comment by g-brodiei** [comment]
Seeing the same Deprecated notice on our website as well.

**Comment by g-brodiei** [comment]
@pguillard  Upgrading spatie/schema-org to 3.11 fixed our error message.
Seems to be fixed on #174, please confirm.
