### ISSUE TITLE
Support for custom @context

### ISSUE THREAD

**Issue by paulofreitas** [spatie/schema-org#185]
It would be really useful to have support for custom `@context` objects as outlined in the JSON-LD spec starting from chapter [3.1 The Context](https://www.w3.org/TR/json-ld11/#the-context).

I used to use Schema.org vocabulary with a custom base IRI to simplify the linking identifiers:

```json
{
    "@context": {
        "@vocab": "https://schema.org/",
        "@base": "https://domain.com/"
    }
}
```
There's a lot of other use-cases when using custom `@context` objects.

Unfortunately, `Schema::context()` only accepts a string, ideally it would also take an array and serialize it as needed:

```php
$graph = new Graph([
    '@vocab' => 'https://schema.org/',
    '@base' => 'https://domain.com/',
]);
```

If this is not intended, is there anything we can do to achieve this?

**Edit:**

For now I'm overloading `Graph` implementation as it fits my needs:

```php
class Graph extends \Spatie\SchemaOrg\Graph
{
    public function __construct(array|string $context = null)
    {
        if (is_array($context)) {
            $context = json_encode($context);
        }

        parent::__construct($context);
    }

    public function toArray(): array
    {
        $graph = parent::toArray();
        $graph['@context'] = json_decode($graph['@context']);

        return $graph;
    }
}
```
Please let me know if there's an easier way to do this!

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/3.13.0
