### ISSUE TITLE
Why the PHP deprecations for what is essentially a data object?

### ISSUE THREAD

**Issue by dooferorg** [spatie/schema-org#186]
I'm not sure why there seems to be a very ongoing deprecation of allowing this project to be updated on older PHP versions. I am in need of adding later schema.org entries to a system that is stuck using an older version of PHP (no, I don't want a discussion as to why everything should be updated when you say it should be - sometimes that's not feasible for other reasons)

My question/issue is why what is essentially a data object to JSON renderer would need to 'deprecate' anything and make it inaccessible for a seemingly arbitrary reason?

**Comment by Gummibeer** [comment]
As every PHP Version increases the maintenance  overhead and reduces the available features.

**Comment by dooferorg** [comment]
For others finding this and in case it helps anyone, I was able to check out the repository, set the namespacing and use the latest objects just fine with PHP 7.1 whereas I wasn't able to with the 'enforced versioning' of composer.
