### ISSUE TITLE
Recursion on setting referenced

### ISSUE THREAD

**Issue by JamesFX2** [spatie/schema-org#195]
I have a webPage schema, I have a product schema. I set mainEntityOfPage of the product schema to the webPage schema via referenced method. I set the about property of the webPage schema to the product via referenced method. Recursion. Infinite loop. SegFault. 256 function calls. 

     $productSchema->mainEntityOfPage($itemPage->referenced());
     $itemPage->about($productSchema->referenced());

I understand why this is happening but literally I just want it to link to each other via the graph.

**Comment by pinchukd** [comment]
try reference only one of connections above
