### ISSUE TITLE
Why do I have problems with Google Console detecting query-input ?

### ISSUE THREAD

**Issue by gabrielfigueroa** [spatie/schema-org#214]
![Screenshot 2024-01-12 073536](https://github.com/spatie/schema-org/assets/3842281/92699c0d-5c80-4eb0-a2e2-733e5109e743)

**Comment by Gummibeer** [comment]
There's no `query-input` or `queryInput` property in schema.org
https://schema.org/SearchAction only has a `query` property.

Besides that: this is a schema.org fluent builder and Google has proven several times that they don't 100% stick to schema.org spec. So if you have any problems with Google - they should be asked.

**Comment by ghnp5** [comment]
Use this:

`->setProperty('query-input', 'required search_q=search_term_string')`
