### ISSUE TITLE
Graph docblock causes Psalm memory exhaustion.

### ISSUE THREAD

**Issue by TomPeters-NL** [spatie/schema-org#215]
During  static code analysis, Psalm seems to run out of memory solely due to the presence of the `Graph` class, presumably due to the amount of references to other classes in the `@method` docblock.

Is this a known issue and/or could this be fixed, or are our options limited to excluding the affected files from Psalm analysis?

**Comment by Gummibeer** [comment]
There's nothing special about it and also no references but only magic methods with defined argument and return types. So this more an issue for psalm.
