### ISSUE TITLE
Array type hints

### ISSUE THREAD

**Issue by bayareawebpro** [spatie/schema-org#22]
Not a bug, but a suggestion:

"SameAs" should accept an array (which does work) but the property should be changed in the php doc block to reflect this.  Currently it says this type is not expected but it still outputs properly.

```
            ->sameAs([
                    "https://www.facebook.com",
                    "https://twitter.com"
            ])
```

**Comment by sebastiandedeyne** [comment]
While this is correct, this package exactly follows the spec, which doesn't explicitly mention an array, so at the moment we can't accurately determine which methods should have `array` in the docs and which shouldn't.

Unless the Schema simply allows this everywhere? Hard to find a source on how arrays should be handled...

**Comment by bayareawebpro** [comment]
I tried this with locations as well which also worked.  Seems they do allow the array type in several places but you're right it's not documented well.  Been checking my work against the structured data testing tool and so far so good.  Thank you so much for this well designed library.  Extremely useful.

**Comment by sebastiandedeyne** [comment]
If this was a "normal" library I'd add it, but since the code is generated based on the spec, I don't really want to have to maintain exceptions, unless there's a bug.

**Comment by sebastiandedeyne** [comment]
As of `1.4.0`, every property has array type hints included.
