### ISSUE TITLE
Insufficient handling of multitype parameters

### ISSUE THREAD

**Issue by nibra** [spatie/schema-org#32]
The generated code contains wrong type declaration for parameters, if the original type contains alternatives like `int|float`. Example is the `numberOfRooms` parameter in `Accommodation.php`.

Currently, the parameter DocBlock line (line 42) is rendered as 

    @param float|int|float|int[]|QuantitativeValue|QuantitativeValue[] $numberOfRooms

It should be

    @param float|int|float[]|int[]|QuantitativeValue|QuantitativeValue[] $numberOfRooms

**Comment by sebastiandedeyne** [comment]
Released a fix in `1.4.1` :)
