### ISSUE TITLE
DateTime isn't formatted in ISO 8601

### ISSUE THREAD

**Issue by johnnelus** [spatie/schema-org#45]
DateTimes are formatted in DateTime::ISO8601 which isn't ISO 8601. It should be DateTime::ATOM.

See docs for both ISO8601 and ATOM.
http://php.net/manual/en/class.datetime.php#datetime.constants.atom

**Comment by sebastiandedeyne** [comment]
(the PR isn't tagged yet, gonna release a new version tomorrow)
