### ISSUE TITLE
Implementation of schema.org/Date

### ISSUE THREAD

**Issue by olivermack** [spatie/schema-org#47]
Hey,

First of all, thanks for the lib! :)
Now, I'm curious if there's a special reason why the [Date](http://schema.org/Date) object has not yet been implemented. If there's no reason I'm happy to contribute that because I could make use of it in my project.

Best

**Comment by sebastiandedeyne** [comment]
Hi @olivermack,

`Date` doesn't need an implementation in this library, because it's a schema.org "DataType", not a "Thing". What are you missing, could you share a snippet of what you'd like to do?

**Comment by olivermack** [comment]
Hey @sebastiandedeyne 
Thanks for the quick feedback. Yeah, you're right, I missed that. I was confusing the output on the doc page a bit.
Basically I was looking for a Model that can represent a date range - while browsing through schema.org I saw "startDate" and "endDate" appearing on the specs of Date - but it was only about the "use cases" of Date.

Unfortunately it does not seems as if there's an appropriate abstraction for stuff that has a start and and an end. 

But never mind, I'll close this issue, it's indeed not part of this lib ;).

Best
