### ISSUE TITLE
PHP 7.0 requirement is holding back some people form using this library

### ISSUE THREAD

**Issue by GChester** [spatie/schema-org#56]
PHP 7.0 requirement is holding back some people from using this library.

We have almost .5GB of PHP source and upgrading to PHP 7.0 will probably take months of conversion that we simply cannot afford at this time.

I know sometimes developers get focused on new shiny objects and want the latest and greatest version but many of us running apps in a business cannot simply upgrade to newer version easily.

Is PHP 7.0 really necessary for a simple library to generate Schema?

**Comment by sebastiandedeyne** [comment]
Hi @GChester,

PHP 7.0 isn't shiny new anymore, it's almost 3 years old, and isn't even actively supported anymore (http://php.net/supported-versions.php)

I understand that it can be hard to upgrade, but dealing with older PHP versions would require a lot of extra maintenance and overhead from us, for something we don't need.

This library is licensed under the MIT license, feel free to create a fork and modify this package to suit your needs.

**Comment by GChester** [comment]
If 7.0 is not a "Shiney Object" then why are versions of 5.6 still produced.

http://php.net/archive/2018.php#id2018-04-26-4

**Comment by sebastiandedeyne** [comment]
As shown in my original link, those are minimal critical security releases. PHP 5.6 and 7.0 are _not actively supported_ anymore. 

As of december 2018, using these versions in production will be considered a security risk.

**Comment by GChester** [comment]
You seem very talented! After a quick look at your website and other projects, you appear to do quality work so congratulations...

It is great you have the luxury of only working with the newest versions and being prepared for security risks that will happen at a future date.

Unfortunately, a very large portion of the business world has to play with our old toys and cannot focus on the "Leading Edge" of technology or should we call it the "Bleeding Edge" of technology where most of the problems exist.

Undoubtedly you would probably find more momentum for your projects appealing to a large crowd of people.

As is it is too much investment to retool (fork).
