### ISSUE TITLE
@id on BreadcrumbList

### ISSUE THREAD

**Issue by floflock** [spatie/schema-org#59]
Hi!

Great package!
I've found one thing to consider. If you want to build a BreadcrumbList schema, it's not valid by Google because they want a ```@id``` parameter in the ListItem.

See: https://developers.google.com/search/docs/data-types/breadcrumb
```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://example.com/books",
      "name": "Books",
      "image": "http://example.com/images/icon-book.png"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://example.com/books/authors",
      "name": "Authors",
      "image": "http://example.com/images/icon-author.png"
    }
  },{
    "@type": "ListItem",
    "position": 3,
    "item": {
      "@id": "https://example.com/books/authors/annleckie",
      "name": "Ann Leckie",
      "image": "http://example.com/images/author-leckie-ann.png"
    }
  },{
    "@type": "ListItem",
    "position": 4,
    "item": {
      "@id": "https://example.com/books/authors/ancillaryjustice",
      "name": "Ancillary Justice",
      "image": "http://example.com/images/cover-ancillary-justice.png"
    }
  }]
}
</script>
```

I did not want to create a PR, because I do not exactly where this ```@id``` element should be assigned. It's not documented in schema.org, I think.

Possible solution is to add a method on Thing.php:
```php
    /**
     * id parameter for BreadcrumbList for example
     *
     * @param string $id
     *
     * @return static
     */
    public function id($id)
    {
        return $this->setProperty('@id', $id);
    }
```

Other solution is to create a new schema class ```BreadcrumbListItem::class``` and put the ```@id``` property in there with extension of ```ListItem::class```

Looking forward to your answer and happy coding! 👍

**Comment by Gummibeer** [comment]
Following schema.org itself this is done by https://schema.org/identifier this is already available in `Thing` https://github.com/spatie/schema-org/blob/ea9dc677d25fde535540fb4cd4c0ccdbc84732c3/src/Thing.php#L76-L92

The main problem is that all classes are created in a dynamic way. So to solve this issue it's required to add a method in a hardcoded way. 😕

**Comment by florianflock** [comment]
@Gummibeer Yes, the problem is the dynamic class structure. However, my solution works fine for me.

**Comment by Gummibeer** [comment]
And the most major problem I see is that this is something Google related and not the general schema standard.
As a workaround you can call `setPropery` like in your wrapper method directly. I bet that this is the way to go if you want fields that aren't part of schema.org itself.

Or you extend the class and use this one in your code.
I'm curious if this is the only Google related special or if they do have more. If they have more it could be an idea to collect them and see how to get these consumer special things into this library. If it's the only one I would say that it's the easiest thing to call `setProperty` by your own - also to close discussions for every other consumer special thing in an early step.

**Comment by eSilverStrike** [comment]
Hi I have been trying out your package and was trying to figure out breadcrumbs.

Can you give a code example on how to set the @id parameter in each listitem?

I also am have trouble setting more than 1 listitem.

Here is the test code I have so far (currently I am using the thing type  as a substitute)

```
use Spatie\SchemaOrg\Schema;

$breadcrumbs = Schema::BreadcrumbList()
    ->itemListElement(
        Schema::ListItem()
            ->position(1)
            ->item(Schema::Thing()
                ->name('Dresses')
            )
        );

echo $breadcrumbs->toScript(); 
```

What would be the php code needed to generate the JSON-LD example on 

https://schema.org/BreadcrumbList

Thanks

**Comment by Gummibeer** [comment]
A simple call to `setProperty('@id', 'value')` should solve your problem. At the moment there is no specific method to set the ID because of the special-char `@`.
And the fact that `@id` isn't part of the original schema definition - it's only part of what Google wants. Like said above schema only knows `identifier`.

At all this is a tricky question. The code is auto generated by the schema XML - so there is no space/way for custom methods. The only way I see would be a special Google schema XML which adds the method to the breadcrumb-listitem.

**Comment by eSilverStrike** [comment]
Based on the conversation above I figured I needed to use `setProperty('@id', 'value')` but am unsure how to add it to the item parameter and what do I change the `Schema::Thing()` too so the type is not set for the item and the following is returned:

```
    <script type="application/ld+json">
    {
     "@context": "http://schema.org",
     "@type": "BreadcrumbList",
     "itemListElement":
     [
      {
       "@type": "ListItem",
       "position": 1,
       "item":
       {
        "@id": "https://example.com/dresses",
        "name": "Dresses"
        }
      },
      {
       "@type": "ListItem",
      "position": 2,
      "item":
       {
         "@id": "https://example.com/dresses/real",
         "name": "Real Dresses"
       }
      }
     ]
    }
    </script>
```
Could you modify the code in my previous comment for an example?

**Comment by eSilverStrike** [comment]
Thanks!

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/2.6.0
