### ISSUE TITLE
Graph with multiple instances of same type

### ISSUE THREAD

**Issue by Gummibeer** [spatie/schema-org#73]
The `Graph` class #62 allows to keep a single instance of each type in the graph. Sometimes I would like to manage multiple instances of the same type in one graph.

Let's say I would like to create a graph for this package - I would have a `CreativeWork` for the package and would need one `Person` for every contributor/commenter. These persons I could need again as the author of an issue or whatever.
To do so I will have to keep track of the instances in a custom variable `$persons` which is filled by `Schema::person()` and could be reused via `$persons['gummibeer']`. But this isn't as smooth as the workflow of the graph which could manage types in multiple places via object references and I don't have to fill the person record I reference it the first time.

The idea would be to add an optional string identifier to manage multiple instances of the same type in a single graph.

```php
$graph = new Graph();
$graph->person('gummibeer')->name('Tom Witkowski')->alternateName('Gummibeer');
$graph->person('gummibeer');
$graph->person('gummibeer', function(Person $person, Graph $graph) {
    $person->email('dev.gummibeer@gmail.com');
});
```

So far I've planned it this wouldn't be a BC so it could be released as a normal MINOR release. The new optional argument would be handled in `__call()` via checks of `is_string` `is_callable` to map the arguments to the right variable and in the other methods `add`, `has` and so on it would be added as an optional second argument so it won't change the already implemented method calls.
I would only adjust the behavior of `show` and `hide` to allow to show/hide all of a single type and a specific one (with identifier). To do so I would split the values of the identifier
* `null` => all of the given type
* `'default'` (*default*) => the one created if no identifier is given
* `'xyz'` => a specific one

**Comment by metalcamp** [comment]
Any updates on this issue? Anything I can help with?

**Comment by Gummibeer** [comment]
Hey @metalcamp , so far I had no need for it so I haven't proceed here.
Would the described solution be usable for you?

**Comment by Gummibeer** [comment]
I'm working on this now.

the new doc-block for `Graph::__call()`:

```php
    /**
     * This overloads all \Spatie\SchemaOrg\Schema construction methods.
     * You can call them the same like on the \Spatie\SchemaOrg\Schema class.
     * But you can also use the extended signatures:
     *
     * Graph::organisation(): Organisation
     * Graph::organisation('spatie'): Organisation
     * Graph::organisation(function(Organisation $organisation, Graph $graph) {}): Graph
     * Graph::organisation('spatie', function(Organisation $organisation, Graph $graph) {}): Graph
     *
     * @see \Spatie\SchemaOrg\Schema
     *
     * @param string $method
     * @param array $arguments
     *
     * @return $this|Type
     *
     * @throws \ReflectionException
     * @throws \BadMethodCallException
     */
```
