### ISSUE TITLE
Schema type Brand

### ISSUE THREAD

**Issue by nolros** [spatie/schema-org#74]
Per the spec the “Brand” is a child of “Thing > Intangible > Brand” and as such should accept a Thing, whereas you have the injection dependency “organization“ and therefore 

Change to Class:

```
    class Product extends BaseType
```

Current (From):

```
	/**
	 * The brand(s) associated with a product or service, or the brand(s)
	 * maintained by an organization or business person.
	 *
         * @param Brand|Brand[]|Organization|Organization[] $brand
	 *
	 * @return static
	 *
	 * @see http://schema.org/brand
	 */
	public function brand($brand)
	{
	    return $this->setProperty('brand', $brand);
	}
```

Change (To):

```
	/**
	 * The brand(s) associated with a product or service, or the brand(s)
	 * maintained by an organization or business person.
	 *
	 * @param Brand|Brand[]|Thing|Thing[] $brand
	 *
	 * @return static
	 *
	 * @see http://schema.org/brand
	 */
	public function brand($brand)
	{
	    return $this->setProperty('brand', $brand);
	}
```

As always a phenomenal library. Thanks!

**Comment by sebastiandedeyne** [comment]
The source code of this package isn't hand written but automatically generated based on the schemaorg/schemaorg repository.

If something's wrong or missing, you'll need to open an issue over there, then I can regenerate the package with the new types.

And thanks :D
