### ISSUE TITLE
Build and release if rdfa changes

### ISSUE THREAD

**Issue by Gummibeer** [spatie/schema-org#75]
The package should get a new patch release everytime the rdfa changes. This could be done by hand but I think that it would be better to have a cronjob/CI doing the job.
It could be discussed that it should be a minor release instead of a patch one. Otherwise it could be an idea to use composer hooks to generate the types during local package installation and on composer update.

**Comment by Gummibeer** [comment]
https://github.com/github/hub#git-pull-request

**Comment by sebastiandedeyne** [comment]
> Otherwise it could be an idea to use composer hooks to generate the types during local package installation and on composer update.

This sounds a bit scary to me because if the rdfa changes and removes something, your app could suddenly have type errors and pinning a specific version wouldn't solve the issue.

Doing this with a cron sounds like a good idea though 👍

**Comment by atymic** [comment]
If you need any help on this feel free to ping me :)

**Comment by Gummibeer** [comment]
@atymic I've added a bash file #81 feel free to improve it!

**Comment by Gummibeer** [comment]
@atymic I've pushed a fix in #86 feel free to check it.
