### ISSUE TITLE
drop unsupported PHP version support

### ISSUE THREAD

**Issue by Gummibeer** [spatie/schema-org#88]
@sebastiandedeyne Atm we support PHP >=7.0 but [official](https://www.php.net/supported-versions.php) only PHP >=7.2 is fully supported and 7.1 is in security only phase. So we could at least drop PHP7.0 support. And plan to drop PHP7.2 support end of the year.

Or should we support the lowest possible version for all times? This would increase the TravisCI build duration over time.

**Comment by ThomasRedstone** [comment]
There are two ways to look at it, if there are no breaking changes that have been adopted for later versions of PHP, then it could be argued that there is no harm in continuing to support 7.0.
But by doing that it's encouraging developers to use out of support software, and forcing contributors to avoid new language features.
Composer will still install the latest version that was still compatible with the version of PHP that the user is running, so on balance, I think that it's probably better to change to 7.2, and let users who have old versions of PHP use the older release.

**Comment by ThomasRedstone** [comment]
I'm giving a PR for this a go, one thing I spotted is that PHP Unit 6 is out of support, would it be acceptable to remove that in the same PR, or should that be handled via another issue?

**Comment by Gummibeer** [comment]
Related to this is much more than removing the versions. Like you already said by sticking to older versions we can't use modern PHP features. It also prevents us sometimes from upgrading dependencies and so on.
So I will accept everything in this PR that you are willing to do and is related to this topic. To make a review easier I would like to don't have the generated files in the PR. 

=> will check your PR now.

**Comment by Gummibeer** [comment]
@ThomasRedstone thanks for your PRs! 💙 
You nearly have earned your Hacktoberfest t-shirt. 😉  😄

**Comment by ThomasRedstone** [comment]
Haha, I think I'll try and do 7 as I'd feel guilty having those count as 75% of my PRs!
I hope the commits in the nested PRs are okay, rebasing a stand-alone branch would be fine, but when it has been branched from I'm not sure how well it would work when it comes to merging them in.
